name: swigg_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/restaurant1.jpg
    - assets/restaurant2.jpg
    - assets/restaurant3.jpg
    - assets/promo_banner.jpg
    - assets/restaurant4.jpg
    - assets/restaurant5.jpg
    - assets/restaurant6.jpg
  uses-material-design: true